{% set name = "biofilm" %}
{% set version = "0.0.97" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/biofilm-{{ version }}.tar.gz
  sha256: 512a2476441486b64d8477d878a2fd3bbf751766d4782115f79f243088622b51

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - auto-sklearn ==0.14.2
    - dirtyopts ==0.0.18
    - eden-kernel ==0.3.1348
    - lmz ==0.1.12
    - numpy >=1.22.0
    - python >=3.8
    - scikit-learn >=0.24.2
    - structout ==0.1.44
    - ubergauss ==0.0.43
    - pynisher ==0.6.4

test:
  imports:
    - biofilm
    - biofilm.algo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/smautner/biofilm
  summary: another opts parser
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - smautner
